version: '3.5'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    command: postgres -c listen_addresses='*'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: menu-service
      POSTGRES_DB: menu_db
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    networks:
      - local
    restart: unless-stopped


  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 5050:80
    networks:
      - local
    restart: unless-stopped

  localstack:
    container_name: localstack_main
    image: localstack/localstack
    ports:
      - 4566:4566
      - 4565:4565
      - 4571:4571
      - 4576:4576
      - 4575:4575
    environment:
      - SERVICES=sns,sqs
    volumes:
      - "./localstack.sh:/docker-entrypoint-initaws.d/make-services.sh"
    networks:
      - local

networks:
  local:
    driver: bridge
